spring:
<<<<<<< HEAD
  thymeleaf:
    suffix: .html
=======
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/sampledb
    driver-class-name: org.mariadb.jdbc.Driver
    username: sampledb_user
    password: 1111

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: siwon8783@gmail.com
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true

